In [0]:
from pyspark.sql.functions import explode
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Name_babys').getOrCreate()

spark.read.json('/tmp/rows.json', multiLine=True).select(explode("data").alias("data")).registerTempTable("newdata")
sqlContext.sql("SELECT data[8] AS year, data[9] AS first_name, data[10] AS country, data[11] AS sex, data[12] AS name_count FROM newdata").registerTempTable("babynames")
df_baby_names= spark.sql('Select * from babynames')
df_baby_names.show()